name: Pull Request

on:
  push:
    branches:
    - develop

  pull_request:
    branches:
    - develop
    - release

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Test App
      run: |
        cd app

        yarn install
        yarn build

        python -m http.server -d public 8000 &
        ./node_modules/.bin/cypress run
