name: CI

on:
  pull_request:
    branches:
    - develop
    - release

  push:
    branches:
    - develop
    - release

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Test Appplication
      run: |
        set -e

        cd app
        yarn install
        yarn build

        python -m http.server -d public 8000 &
        ./node_modules/.bin/cypress run

        cd ..

    - name: Test Electron
      run: |
        set -e

        cd electron
        yarn install
        yarn build

        cd ..

    - name: Should Release?
      id: dorelease
      run: |
        ./scripts/should-release.sh

    - name: Install Python Tools
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install bump2version
      if: steps.dorelease.outputs.yes

    - name: Prepare Release
      id: info
      run: |
         echo "Preparing ${RELEASE_KIND} release"

         git config user.email "alcarneyme@gmail.com"
         git config user.name "Alex Carney"

         bumpversion ${RELEASE_KIND}
         release_date=$(date +%Y-%m-%d)

         version=$(jq -r .version app/package.json)
         echo "Version: $version"

         git push origin ${GIT_BRANCH}
         git push origin --tags

         echo "::set-env name=VERSION::$version"
         echo "::set-output name=VERSION::$version"

         echo "::set-env name=RELEASE_DATE::$release_date"
         echo "::set-output name=RELEASE_DATE::$release_date"
      if: steps.dorelease.outputs.yes

    - name: Package
      run: |
        set -e
        cd electron

        yarn dist
        ls build

        cd ..

    - name: Export release assets
      id: assets
      run: |
        deb=$(find electron/build/ -name '*.deb' -exec basename {} \;)
        echo $deb
        echo "::set-output name=deb::$deb"

        snap=$(find electron/build/ -name '*.snap' -exec basename {} \;)
        echo $snap
        echo "::set-output name=snap::$snap"

    - name: Upload Site Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          name: 'app'
          path: app/public

    - name: Upload Deb Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          name: 'deb'
          path: electron/build/${{ steps.assets.outputs.deb }}

    - name: Upload Snap Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
          name: 'snap'
          path: electron/build/${{ steps.assets.outputs.snap }}

    - name: Create Release
      id: release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.info.outputs.VERSION }}
        release_name: v${{ steps.info.outputs.VERSION}} - ${{ steps.info.outputs.RELEASE_DATE }}
        draft: false
        prerelease: steps.dorelease.outputs.develop
      if: steps.dorelease.outputs.yes

    - name: Publish Deb
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: electron/build/${{ steps.assets.outputs.deb }}
        asset_name: ${{ steps.assets.outputs.deb }}
        asset_content_type: application/octet-stream
      if: steps.dorelease.outputs.yes

    - name: Publish Snap
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: electron/build/${{ steps.assets.outputs.snap }}
        asset_name: ${{ steps.assets.outputs.snap }}
        asset_content_type: application/octet-stream
      if: steps.dorelease.outputs.yes

    - name: Publish to Snapstore
      uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
        snap: electron/build/${{ steps.assets.outputs.snap }}
        release: ${{ steps.dorelease.outputs.snap_channel }}
      if: steps.dorelease.outputs.yes

    - name: Publish App
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: app/public
        TARGET_FOLDER: ${{ steps.dorelease.outputs.deploy_url }}
      if: steps.dorelease.outputs.yes