name: Release

on:
  push:
    branches:
    - release

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Should Release?
      id: dorelease
      run: |
        ./scripts/should-release.sh


    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
      if: steps.dorelease.outputs.yes


    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      if: steps.dorelease.outputs.yes

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install bump2version
      if: steps.dorelease.outputs.yes

    - name: Prepare Release
      id: info
      run: |
         bumpversion $kind
         release_date=$(date +%Y-%m-%d)

         git push origin --tags

         echo "::set-env name=VERSION::$version"
         echo "::set-output name=VERSION::$version"

         echo "::set-env name=RELEASE_DATE::$release_date"
         echo "::set-output name=RELEASE_DATE::$release_date"
      if: steps.dorelease.outputs.yes

    - name: Install Dependencies
      run: yarn install
      if: steps.dorelease.outputs.yes

    - name: Build Packages
      run: yarn run dist
      if: steps.dorelease.outputs.yes

    - name: Tag Release
      run: |
        commit=$(git rev-parse HEAD)
        # POST a new ref to repo via Github API
        curl -s -X POST https://api.github.com/repos/${{ github.repository }}/git/refs \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d @- << EOF
        {
          "ref": "refs/tags/v$VERSION",
          "sha": "$commit"
        }
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.dorelease.outputs.yes