name: Release

on:
  push:
    branches:
    - release

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Should Release?
      id: dorelease
      run: |
        ./scripts/should-release.sh


    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
      if: steps.dorelease.outputs.yes


    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      if: steps.dorelease.outputs.yes

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install bump2version
      if: steps.dorelease.outputs.yes

    - name: Prepare Release
      id: info
      run: |
         echo "Preparing ${RELEASE_KIND} release"

         git config user.email "alcarneyme@gmail.com"
         git config user.name "Alex Carney"

         bumpversion ${RELEASE_KIND}
         release_date=$(date +%Y-%m-%d)

         echo "::set-env name=VERSION::$version"
         echo "::set-output name=VERSION::$version"

         echo "::set-env name=RELEASE_DATE::$release_date"
         echo "::set-output name=RELEASE_DATE::$release_date"
      if: steps.dorelease.outputs.yes

    - name: Install Dependencies
      run: yarn install
      if: steps.dorelease.outputs.yes

    - name: Build Packages
      run: yarn run dist
      if: steps.dorelease.outputs.yes

    - name: Tag Release
      run: |
        git push origin --tags
      if: steps.dorelease.outputs.yes